import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const links = [
    {
      link: "/posts/new",
      text: "作成",
    },
    {
      link: "/posts",
      text: "一覧",
    }
  ]
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
	<header>
	  {links.map((x) => (
	    <div>
	      <a href={x.link}>{x.text}</a>
	    </div>
	    ))}
	</header>
        <main>
	  {children}
	</main>
      </body>
    </html>
  );
}
